version: '2'
services:
  postgresql:
    image: postgres:9.5
    command: postgres
    volumes:
      - ./src/migrations:/docker-entrypoint-initdb.d
  test:
    volumes:
      - .:/usr/src/app
    build:
      context: .
    links:
      - postgresql
    depends_on:
      - postgresql
    environment:
      - NODE_ENV=testing
      - DATABASE_URI=postgres://redvelvet@postgresql/rv_api_testing
      - DATABASE_INITIALIZATION_URI=postgres://postgres@postgresql/template1
